# Tutorial here: https://medium.com/@harmittaa/travis-ci-android-example-357f6e632fc4

language: android
sudo: required
jdk:
  - oraclejdk8

android:
  components:
      - tools
      - platform-tools
      - tools

      - build-tools-26.0.2
      - android-26
      - addon-google_apis-google-26
      - extra-google-google_play_services
      - extra-android-support
      - extra-google-m2repository
      - extra-android-m2repository

script: ./gradlew build connectedCheck